linters:
  enable-all: true

  disable:
    - paralleltest
    - testpackage
    - nlreturn
    - exhaustive
    - exhaustivestruct
    - gochecknoglobals
    - gochecknoinit
    - cyclop
    - goerr113
    - gofumpt
    - stylecheck
    - forbidigo
    - godot
    - maligned
    - interfacer
    - scopelint
    - golint